# create user
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
    "name":"parilsanghvi",
    "email": "parilsanghvi0510@gmail.com",
    "password": "Sanghvi@4",
    "avatar":{
        "public_id":"sample image",
        "url":"sample url"
    }
}
###
# login
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "email": "parilsanghvi@gmail.com",
    "password": "Sanghvi@4"
}
###
#logout user
GET http://localhost:8080/api/v1/logout
###
#forgot password
POST  http://localhost:8080/api/v1/password/forgot
Content-Type: application/json

{
    "email": "parilsanghvi@gmail.com"
}
###
#reset password
PUT  http://localhost:8080/api/v1/password/reset/b328357309318b178e48dc744c021ab7f2aa24d4
Content-Type: application/json

{
    "password": "00000000",
    "confirmPassword": "00000000"
}