#create order
POST http://localhost:8080/api/v1/order/new
Content-Type: application/json

{
    "itemsPrice": "200",
    "taxPrice": "36",
    "shoppingPrice": "100",
    "totalPrice": "336",
    "orderItems":[
        {
            "product" : "61b4cff6102477046e5f77ac",
            "name": "product2",
            "price": 1500,
            "image": "sample image",
            "quantity": 1
        }
    ],
    "shippingInfo":{
        "address":"44/524 chitrakut appt",
        "city":"ahmedabad",
        "state":"gujarat",
        "country":"india",
        "pinCode": 380063,
        "phoneNo":9316174149
    },
    "paymentInfo":{
        "id":"sample payment info",
        "status":"succeeded"
    }
}
###
#find my orders
GET  http://localhost:8080/api/v1/orders/me
###
#find order by id
GET  http://localhost:8080/api/v1/order/61bd8743ab17f3181031c700
###
#find all orders
GET  http://localhost:8080/api/v1/admin/orders
###
#update order 
PUT   http://localhost:8080/api/v1/admin/order/61bd934e111b5b57fabb81b8
Content-Type: application/json

{
    "status":"Delivered"
}
###
#delete order 
DELETE    http://localhost:8080/api/v1/admin/order/61bd9319111b5b57fabb81a8